version: '3.8'

services:
  db:
    image: ghcr.io/alimoosavi/postgres:15.3-alpine
    container_name: db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: persian-news
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

volumes:
  postgres_data: