# Generated by Django 4.2.16 on 2024-09-19 19:06

from django.db import migrations


def insert_news_sources(apps, schema_editor):
    NewsSource = apps.get_model('rag_app', 'NewsSource')
    news_sources = [
        NewsSource(
            name='IRNA',
            base_url='https://www.irna.ir/archive'
        )
    ]

    NewsSource.objects.bulk_create(news_sources)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("rag_app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(insert_news_sources, reverse),
    ]
