# Generated by Django 4.2.16 on 2024-09-22 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rag_app", "0003_auto_20240919_1911"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="news",
            name="news_category",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="news",
            name="news_source",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="news",
            name="news_link",
            field=models.CharField(max_length=400),
        ),
        migrations.AlterUniqueTogether(
            name="news",
            unique_together={("news_source", "news_category", "news_link")},
        ),
    ]
