# Generated by Django 4.2.16 on 2024-10-03 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rag_app", "0004_news_date_news_news_category_news_news_source_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="newslink",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="news",
            unique_together={("news_source", "news_link")},
        ),
        migrations.RemoveField(
            model_name="news",
            name="news_category",
        ),
        migrations.RemoveField(
            model_name="newslink",
            name="category",
        ),
        migrations.DeleteModel(
            name="NewsCategory",
        ),
    ]
