# Generated by Django 4.2.16 on 2024-10-03 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rag_app", "0005_alter_newslink_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslink",
            name="source",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="links",
                to="rag_app.newssource",
            ),
            preserve_default=False,
        ),
    ]
