# Generated by Django 4.2.16 on 2024-10-04 19:58

from django.db import migrations


def insert_trading_view_source(apps, schema_editor):
    NewsSource = apps.get_model('rag_app', 'NewsSource')
    NewsSource.objects.create(name='TradingView',
                              base_url='https://www.tradingview.com/news')


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("rag_app", "0006_newslink_source"),
    ]

    operations = [
        migrations.RunPython(insert_trading_view_source, reverse),
    ]
