# Generated by Django 4.2.16 on 2024-10-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rag_app", "0007_auto_20241004_1958"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="has_processed",
            field=models.BooleanField(default=False),
        ),
    ]
